export const MOCK_USERS = [
  {
    id: "1",
    email: "gigsdev007@gmail.com",
    password: "demo123",
    username: "gigsdev007",
    role: "super_admin",
    fullName: "Super Admin",
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "2",
    email: "admin@ituwa.com",
    password: "admin123",
    username: "admin",
    role: "admin",
    fullName: "Admin User",
    createdAt: new Date("2025-01-05"),
  },
  {
    id: "3",
    email: "user@ituwa.com",
    password: "user123",
    username: "learner",
    role: "user",
    fullName: "Learner User",
    createdAt: new Date("2025-01-10"),
  },
]

export const MOCK_REGISTERED_USERS = [
  {
    id: "1",
    email: "gigsdev007@gmail.com",
    username: "gigsdev007",
    role: "super_admin",
    fullName: "Super Admin",
    createdAt: "2025-01-01",
    status: "active",
    lessonsCompleted: 15,
    totalScore: 850,
  },
  {
    id: "2",
    email: "sarah.dev@example.com",
    username: "sarah_dev",
    role: "user",
    fullName: "Sarah Development",
    createdAt: "2025-02-10",
    status: "active",
    lessonsCompleted: 8,
    totalScore: 420,
  },
  {
    id: "3",
    email: "mike.trader@example.com",
    username: "mike_trader",
    role: "user",
    fullName: "Mike Trader",
    createdAt: "2025-02-15",
    status: "active",
    lessonsCompleted: 12,
    totalScore: 680,
  },
  {
    id: "4",
    email: "alice.web3@example.com",
    username: "alice_web3",
    role: "user",
    fullName: "Alice Web3",
    createdAt: "2025-02-20",
    status: "inactive",
    lessonsCompleted: 3,
    totalScore: 150,
  },
  {
    id: "5",
    email: "bob.crypto@example.com",
    username: "bob_crypto",
    role: "user",
    fullName: "Bob Crypto",
    createdAt: "2025-02-22",
    status: "active",
    lessonsCompleted: 20,
    totalScore: 1200,
  },
]
